name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Python version
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

#       # Install dependencies using requirements.txt
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
# 
#       # Run tests
#       - name: Run tests with pytest
#         run: |
#           export PYTHONPATH=$(pwd)
#           pytest test/
# 